apiVersion: v1
kind: Pod
metadata:
  name: pod-images
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 8000