apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hafzan-kubernetes
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "pods/logs", "describe", "create"]