apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-user
  namespace: default
rules:
- apiGroups: [""]
  verbs: ["get", "list", "logs", "create"]
  resources: ["pods", "pods/log"]