apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-user-binding
  namespace: default
subjects:
- kind: User
  name: mikhail  # Name of the user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-user  # Name of the role
  apiGroup: rbac.authorization.k8s.io