apiVersion: v1
kind: Pod
metadata:
  name: myservice
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
  nodeSelector:
    name: node01