apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdAo=                 
  MYSQL_DATABASE: bXlzcWwK                 
  MYSQL_USER: bmF5bGkK             
  MYSQL_PASSWORD: cm9vdAo=                 
