apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: "dbservice"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: mysql:latest
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: db
---

apiVersion: v1
kind: Service
metadata:
  name: dbservice
  labels:
    app: dbservice
spec:
  ports:
  - port: 80
    name: db
  clusterIP: None
  selector:
    app: dbservice

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_DATABASE: Y2NzZA==
  MYSQL_ROOT_PASSWORD: MTIzNDU2Nzg5
  MYSQL_USER: Y2NzZA==
  MYSQL_PASSWORD: MTIzNDU2Nzg5