apiVersion: v1
kind: Secret
metadata:
  name: credentials
data:
  MYSQL_ROOT_PASSWORD: "YWRpYjEyMw==" 
  MYSQL_DATABASE: "bXlzcWw="
  MYSQL_PASSWORD: "YWRpYjEyMw=="
  MYSQL_USER: "YWRpYmFrbm9vcg=="


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: Mysql
  labels:
    app: Mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Mysql
  template:
    metadata:
      labels:
        app: Mysql
    spec:
      containers:
      - name: Mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_USER      