kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: web
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql # must match .spec.template.metadata.labels
  serviceName: "mysql-service"
  replicas: 3 # number of replicas
  minReadySeconds: 10 # seconds a pod must be ready before it's considered available
  template:
    metadata:
      labels:
        app: mysql # must match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:latest # Use a specific MySQL image version for production
        ports:
        - containerPort: 3306
          name: web
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_root_password