apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2hhaGly
  MYSQL_DATABASE: c2hhaGly
  MYSQL_USER: c2hhaGly
  MYSQL_PASSWORD: c2hhaGly