apiVersion: v1
data:
  MYSQL_DATABASE: ZGF0YWJhc2U=
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: cGFzc3dvcmQ=
kind: Secret
metadata:
  creationTimestamp: null
  name: secrets
