apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jenkins
  name: jenkins
  namespace: web-frontend
spec:
  containers:
  - image: jenkins:latest
    name: jenkins
    ports:
    - containerPort: 8080
    - containerPort: 50000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}