apiVersion: v1
kind: namespace
metadata:
  name: web-frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: web-frontend
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts