apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app_env_stage: dev
spec:
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 80
