apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    args:
    livenessProbe:
      httpGet:
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3