apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: qq3Image
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80