apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
  namespace: default
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /pv/data-analytics